AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - gemfiles/**/*

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 15

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EvalWithLocation:
  Exclude:
    - spec/**/*

Style/RescueModifier:
  Exclude:
    - spec/**/*

Layout/MultilineMethodCallIndentation:
  Exclude:
    - spec/**/*
