AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - gemfiles/**/*

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Exclude:
    - lib/bunny_publisher/mandatory.rb

Metrics/ModuleLength:
  Exclude:
    - lib/bunny_publisher/mandatory.rb

Metrics/MethodLength:
  Max: 15
  Exclude:
    - lib/bunny_publisher/base.rb
    - lib/bunny_publisher/mandatory.rb

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EvalWithLocation:
  Exclude:
    - spec/**/*

Style/RescueModifier:
  Exclude:
    - spec/**/*

Layout/MultilineMethodCallIndentation:
  Exclude:
    - spec/**/*
