---
dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
gemfile:
  - gemfiles/bunny_2.10.x.gemfile
  - gemfiles/bunny_2.x.gemfile

before_install: gem install bundler
before_script:
  - ".ci/install_rabbitmq"
bundler_args: --jobs 3 --retry 3
