---
dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
gemfile:
  - gemfiles/bunny_2.10.x.gemfile
  - gemfiles/bunny_2.x.gemfile
  - gemfiles/activesupport_4.2.x.gemfile

matrix:
  exclude:
    - rvm: 2.7.2
      gemfile: gemfiles/activesupport_4.2.x.gemfile

before_install: gem install bundler
before_script:
  - ".ci/install_rabbitmq"
bundler_args: --jobs 3 --retry 3
